### ISSUE TITLE
Grabbing Skin

### ISSUE THREAD

**Issue by VinxzMc** [Now-this-is-crazy/SkinGrabber#4]
Grabbing Skin!
-----------------------
Skin: VinxzMc
Decoded Skin: {
  "timestamp" : 1713001648888,
  "profileId" : "7589b11bfbef42179456702b0b81a83c",
  "profileName" : "NowThisIsCrazy",
  "signatureRequired" : true,
  "textures" : {
    "SKIN" : {
      "url" : "https://imgur.com/14iOXzX"
    }
  }
}
URL: https://imgur.com/14iOXzX
-----------------------

**Comment by RedVortexDev** [comment]
Hello there,
I don't quite understand what you meant, could you please elaborate on the issue?
